version: '3.3'
services:
  java-rest-api:
    container_name: java-rest-api
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "cassandra1"
    environment:
      - "REPLICATION_FACTOR=2"
    restart: on-failure


  cassandra-seed:
    container_name: cassandra-seed
    image: cassandra:latest
    ports:
      - "9043:9043"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=election_database"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"

  cassandra1:
    container_name: cassandra-node1
    image: cassandra:latest
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=election_database"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    depends_on:
      - "cassandra-seed"